services:
   appsmith:
     image: index.docker.io/appsmith/appsmith-ee
     container_name: appsmith
     ports:
         - "80:80"
         - "443:443"
     volumes:
         - ./stacks:/appsmith-stacks
     networks:
         - app-network
     restart: unless-stopped

   fastify-backend:
     build: 
       context: ../fastify-backify
     container_name: fastify-backend
     ports:
         - "3000:3000"
     environment:
         - DATABASE_URL=${DATABASE_URL}
         - PORT=3000
     networks:
         - app-network
     restart: unless-stopped

networks:
  app-network:
    driver: bridge